### ISSUE TITLE
Force push on approved PR doesn't invalidate FurtherReview

### ISSUE THREAD

**Issue by jaumann** [underarmour/further-review#251] opened 2017-08-11 19:33 UTC
I noticed this on https://github.ua.com/harbour/service-data-feeds/pull/51/. If a PR is approved via FurtherReview, but the PR is not merged yet, if the committer squashes and force pushes a change to the code base, the Further Review is not invalidated.

### Steps to Reproduce
1) Open PR
2) Fully approve per Further Review
3) Squash and force push a change to the source branch of the PR
4) Notice that the PR is still approved and able to be merged

**Comment by kjvalencik** [comment] 2017-08-11 19:35
Duplicate of https://github.com/underarmour/further-review/issues/34

**Closed by kjvalencik** 2017-08-11 19:35 UTC
